### ISSUE TITLE
Unusual navigation bar behavior

### ISSUE THREAD

**Issue by ericluap** [lloyd-secretary/lloyd-site#31]
The issue:
Click on "Rotation"
The navigation bar now displays "Home", "Account", and "Logout".
Only clicking on "Account" brings you back to the original navigation bar.

This feels weird because none of the other navigation bar buttons cause this change.

**Comment by pranavpatil1** [comment]
fineeeeee I fixed it for you

lol yeah remnant of coding this in a rush good catch
